
import { Tool, ToolCategory } from './types';

export const TOOLS: Tool[] = [
  // PDF TOOLS
  { id: 'pdf-reader', name: 'PDF Reader', description: 'View and read PDF files instantly.', category: ToolCategory.PDF, icon: '📖' },
  { id: 'pdf-merge', name: 'PDF Merge', description: 'Combine multiple PDF files into one.', category: ToolCategory.PDF, icon: '🔗' },
  { id: 'pdf-to-jpg', name: 'PDF to JPG', description: 'Convert PDF pages to high-quality images.', category: ToolCategory.PDF, icon: '🖼️' },
  { id: 'pdf-to-word', name: 'PDF to Word', description: 'Extract text and convert PDF to Docx format.', category: ToolCategory.PDF, icon: '📝' },
  { id: 'pdf-to-excel', name: 'PDF to Excel', description: 'Convert PDF tables to editable Excel sheets.', category: ToolCategory.PDF, icon: '📊' },
  { id: 'pdf-compress', name: 'PDF Compressor', description: 'Reduce PDF file size without losing quality.', category: ToolCategory.PDF, icon: '🗜️' },
  { id: 'pdf-reduce', name: 'PDF Reducer', description: 'Optimize and reduce document weight.', category: ToolCategory.PDF, icon: '📉' },
  { id: 'pdf-resizer', name: 'PDF Resizer', description: 'Change PDF page dimensions and scale.', category: ToolCategory.PDF, icon: '📐' },
  { id: 'pdf-conv', name: 'PDF Converter', description: 'Convert files to and from PDF format.', category: ToolCategory.PDF, icon: '🔄' },

  // VIDEO TOOLS
  { id: 'video-gen', name: 'AI Video Generator', description: 'Create cinematic videos from text prompts using Veo.', category: ToolCategory.VIDEO, icon: '🎬' },
  { id: 'video-trim', name: 'Video Trimmer', description: 'Cut and trim video clips to the perfect length.', category: ToolCategory.VIDEO, icon: '✂️' },

  // IMAGE TOOLS
  { id: 'img-png', name: 'Image to PNG', description: 'Convert any image format to PNG.', category: ToolCategory.IMAGE, icon: '🖼️' },
  { id: 'img-jpg', name: 'Image to JPG', description: 'Convert images to high-quality JPG.', category: ToolCategory.IMAGE, icon: '📸' },
  { id: 'img-resize', name: 'Image Resizer', description: 'Resize images by width and height.', category: ToolCategory.IMAGE, icon: '📐' },
  { id: 'img-compress', name: 'Image Compressor', description: 'Reduce file size while keeping quality.', category: ToolCategory.IMAGE, icon: '🗜️' },
  { id: 'img-base64', name: 'Image to Base64', description: 'Convert image to base64 string.', category: ToolCategory.IMAGE, icon: '📄' },
  { id: 'qr-gen', name: 'QR Code Generator', description: 'Generate QR codes for text/URLs.', category: ToolCategory.IMAGE, icon: '📱' },
  
  // SEO TOOLS
  { id: 'meta-gen', name: 'Meta Tag Generator', description: 'Create SEO-friendly meta tags.', category: ToolCategory.SEO, icon: '🏷️' },
  { id: 'word-counter', name: 'Word Counter', description: 'Count words, chars, and paragraphs.', category: ToolCategory.TEXT, icon: '✍️' },
  { id: 'json-format', name: 'JSON Formatter', description: 'Prettify and validate JSON code.', category: ToolCategory.DEV, icon: '📦' },
  { id: 'color-picker', name: 'Color Picker', description: 'Pick colors and get hex/rgb codes.', category: ToolCategory.DEV, icon: '🎨' },
  
  // MATH & CALCULATORS
  { id: 'bmi-calc', name: 'BMI Calculator', description: 'Calculate Body Mass Index.', category: ToolCategory.MATH, icon: '⚖️' },
  { id: 'age-calc', name: 'Age Calculator', description: 'Calculate precise age in years/days.', category: ToolCategory.MATH, icon: '🎂' },
  { id: 'percentage-calc', name: 'Percentage Calculator', description: 'Quick percentage calculations.', category: ToolCategory.MATH, icon: '📊' },
  { id: 'tip-calc', name: 'Tip Calculator', description: 'Calculate split bills and tips.', category: ToolCategory.MATH, icon: '💵' },
  
  // UNIT CONVERTERS
  { id: 'len-conv', name: 'Length Converter', description: 'Convert between m, km, miles, etc.', category: ToolCategory.UNIT, icon: '📏' },
  { id: 'weight-conv', name: 'Weight Converter', description: 'Convert kg, lbs, oz, etc.', category: ToolCategory.UNIT, icon: '🏋️' },
  { id: 'temp-conv', name: 'Temp Converter', description: 'Celsius to Fahrenheit and Kelvin.', category: ToolCategory.UNIT, icon: '🌡️' },
  
  // SECURITY
  { id: 'pass-gen', name: 'Password Generator', description: 'Generate strong, secure passwords.', category: ToolCategory.SECURITY, icon: '🔐' },
  { id: 'hash-gen', name: 'SHA256 Generator', description: 'Generate SHA256 hashes.', category: ToolCategory.SECURITY, icon: '🔑' },
  
  // SOCIAL
  { id: 'yt-thumb', name: 'YouTube Thumbnail', description: 'Download video thumbnails.', category: ToolCategory.SOCIAL, icon: '📺' },
  { id: 'emoji-key', name: 'Emoji Keyboard', description: 'Find and copy any emoji.', category: ToolCategory.SOCIAL, icon: '😀' },

  // MISC
  { id: 'lorem-gen', name: 'Lorem Ipsum', description: 'Generate placeholder text.', category: ToolCategory.TEXT, icon: '📜' },
  { id: 'case-conv', name: 'Case Converter', description: 'Upper, lower, title case converter.', category: ToolCategory.TEXT, icon: '🔠' },
  { id: 'json-to-csv', name: 'JSON to CSV', description: 'Convert JSON data to CSV format.', category: ToolCategory.DEV, icon: '📊' },
  { id: 'base64-text', name: 'Base64 Text', description: 'Encode or decode text to Base64.', category: ToolCategory.DEV, icon: '📝' },
  { id: 'random-num', name: 'Random Number', description: 'Generate random numbers in range.', category: ToolCategory.MISC, icon: '🎲' },
  { id: 'flip-coin', name: 'Flip a Coin', description: 'Heads or Tails simulator.', category: ToolCategory.MISC, icon: '🪙' },
  { id: 'ai-chat', name: 'AI Chatbot', description: 'Ask Gemini anything.', category: ToolCategory.MISC, icon: '🤖' },
  { id: 'bill-calc', name: 'Electric Bill Calc', description: 'Estimate monthly electricity cost.', category: ToolCategory.MATH, icon: '⚡' },
  { id: 'leap-year', name: 'Leap Year Checker', description: 'Check if a year is a leap year.', category: ToolCategory.MATH, icon: '📅' },
  { id: 'unit-data', name: 'Data Storage Conv', description: 'MB to GB to TB converter.', category: ToolCategory.UNIT, icon: '💾' },
  { id: 'unit-speed', name: 'Speed Converter', description: 'Km/h to MPH to Knots.', category: ToolCategory.UNIT, icon: '🏃' },
  { id: 'unit-volume', name: 'Volume Converter', description: 'Liters, gallons, cups.', category: ToolCategory.UNIT, icon: '🧪' },
  { id: 'unit-pressure', name: 'Pressure Converter', description: 'Bar, PSI, Pascal.', category: ToolCategory.UNIT, icon: '🌪️' },
  { id: 'unit-angle', name: 'Angle Converter', description: 'Degrees to Radians.', category: ToolCategory.UNIT, icon: '📐' },
  { id: 'unit-energy', name: 'Energy Converter', description: 'Joules to Calories.', category: ToolCategory.UNIT, icon: '🔋' },
  { id: 'url-short', name: 'URL Shortener', description: 'Quickly shorten long URLs.', category: ToolCategory.SECURITY, icon: '🔗' },
  { id: 'ip-lookup', name: 'IP Geolocation', description: 'Find details about an IP.', category: ToolCategory.SECURITY, icon: '🌍' },
  { id: 'whois', name: 'Whois Lookup', description: 'Check domain ownership.', category: ToolCategory.SECURITY, icon: '🔍' },
  { id: 'sitemap-gen', name: 'Sitemap Gen', description: 'Generate XML sitemaps.', category: ToolCategory.SEO, icon: '🗺️' },
  { id: 'robots-gen', name: 'Robots.txt Gen', description: 'Generate robots.txt files.', category: ToolCategory.SEO, icon: '🤖' },
  { id: 'html-md', name: 'HTML to MD', description: 'HTML to Markdown converter.', category: ToolCategory.DEV, icon: '✍️' },
  { id: 'css-min', name: 'CSS Minifier', description: 'Minify CSS files instantly.', category: ToolCategory.DEV, icon: '🎨' },
  { id: 'js-min', name: 'JS Minifier', description: 'Minify JavaScript code.', category: ToolCategory.DEV, icon: '📜' },
  { id: 'sql-format', name: 'SQL Formatter', description: 'Beautify SQL queries.', category: ToolCategory.DEV, icon: '💾' },
  { id: 'htaccess-gen', name: 'htaccess Gen', description: 'Generate redirect rules.', category: ToolCategory.DEV, icon: '⚙️' },
  { id: 'md-html', name: 'MD to HTML', description: 'Markdown to HTML converter.', category: ToolCategory.DEV, icon: '🌐' },
  { id: 'barcode-gen', name: 'Barcode Gen', description: 'Generate standard barcodes.', category: ToolCategory.MISC, icon: '📋' },
  { id: 'meme-gen', name: 'Meme Generator', description: 'Create custom memes easily.', category: ToolCategory.MISC, icon: '🤡' },
  { id: 'resume-build', name: 'Resume Builder', description: 'Quick resume generator.', category: ToolCategory.MISC, icon: '💼' },
  { id: 'invoice-gen', name: 'Invoice Gen', description: 'Simple billing invoice.', category: ToolCategory.MISC, icon: '🧾' },
  { id: 'biz-name', name: 'Business Name Gen', description: 'Get creative business ideas.', category: ToolCategory.MISC, icon: '🏢' },
  { id: 'lottery-gen', name: 'Lottery Picker', description: 'Generate lucky numbers.', category: ToolCategory.MISC, icon: '🔮' },
  { id: 'dice-roll', name: 'Dice Roller', description: 'Simulate rolling dice.', category: ToolCategory.MISC, icon: '🎲' },
  { id: 'net-speed', name: 'Internet Speed', description: 'Simple latency check.', category: ToolCategory.MISC, icon: '🛰️' },
  { id: 'planner-create', name: 'Daily Planner', description: 'Create your daily schedule.', category: ToolCategory.MISC, icon: '📅' },
  { id: 'wedding-gen', name: 'Wedding Invite', description: 'Template for invitations.', category: ToolCategory.MISC, icon: '💍' },
  { id: 'story-gen', name: 'Story Plot Gen', description: 'Get writing prompts.', category: ToolCategory.MISC, icon: '📖' },
  { id: 'ebook-gen', name: 'E-book Creator', description: 'Basic epub/pdf structure.', category: ToolCategory.MISC, icon: '📚' },
  { id: 'ip-tracker', name: 'IP Tracker', description: 'Monitor IP requests.', category: ToolCategory.MISC, icon: '📍' },
  { id: 'fake-addr', name: 'Fake Address Gen', description: 'Generate test addresses.', category: ToolCategory.MISC, icon: '🏠' },
  { id: 'numerology', name: 'Numerology Calc', description: 'Name to number calculator.', category: ToolCategory.MISC, icon: '🔢' },
  { id: 'gram-check', name: 'Grammar Checker', description: 'Simple grammar validation.', category: ToolCategory.TEXT, icon: '📖' },
  { id: 'text-speech', name: 'Text to Speech', description: 'Read text aloud.', category: ToolCategory.TEXT, icon: '🗣️' },
  { id: 'speech-text', name: 'Speech to Text', description: 'Transcribe audio to text.', category: ToolCategory.TEXT, icon: '🎙️' },
  { id: 'url-codec', name: 'URL Encoder', description: 'Encode/Decode URLs.', category: ToolCategory.TEXT, icon: '🔗' },
  { id: 'fancy-text', name: 'Fancy Text Gen', description: 'Stylized text generator.', category: ToolCategory.TEXT, icon: '✨' },
  { id: 'char-counter', name: 'Character Count', description: 'Count every character.', category: ToolCategory.TEXT, icon: '🔡' },
  { id: 'plagiarism', name: 'Plagiarism Sim', description: 'Check text uniqueness.', category: ToolCategory.TEXT, icon: '📝' },
  { id: 'md5-gen', name: 'MD5 Generator', description: 'Quick MD5 hashing.', category: ToolCategory.SECURITY, icon: '🔐' },
  { id: 'ssl-check', name: 'SSL Checker', description: 'Check domain SSL status.', category: ToolCategory.SECURITY, icon: '🛡️' },
  { id: 'http-head', name: 'HTTP Headers', description: 'Analyze URL headers.', category: ToolCategory.SECURITY, icon: '🌐' },
  { id: 'priv-policy', name: 'Privacy Gen', description: 'Generate privacy policies.', category: ToolCategory.SECURITY, icon: '⚖️' },
  { id: 'insta-down', name: 'Instagram Downloader', description: 'Save Instagram photos.', category: ToolCategory.SOCIAL, icon: '📸' },
  { id: 'twit-video', name: 'Twitter Video', description: 'Download Twitter media.', category: ToolCategory.SOCIAL, icon: '🐦' },
  { id: 'fb-video', name: 'Facebook Video', description: 'Save FB videos.', category: ToolCategory.SOCIAL, icon: '👥' },
  { id: 'tiktok-down', name: 'TikTok Downloader', description: 'Save TikToks.', category: ToolCategory.SOCIAL, icon: '🎵' },
  { id: 'yt-tags', name: 'YouTube Tags', description: 'Extract video tags.', category: ToolCategory.SOCIAL, icon: '🏷️' },
  { id: 'hashtag-gen', name: 'Hashtag Gen', description: 'Trending hashtags.', category: ToolCategory.SOCIAL, icon: '#️⃣' },
  { id: 'social-post', name: 'Post Generator', description: 'Write social captions.', category: ToolCategory.SOCIAL, icon: '✍️' },
  { id: 'twit-count', name: 'Twitter Counter', description: 'Count 280 limit.', category: ToolCategory.SOCIAL, icon: '🐦' },
  { id: 'domain-auth', name: 'Domain Auth', description: 'DA Checker placeholder.', category: ToolCategory.SEO, icon: '🏆' },
  { id: 'backlink', name: 'Backlink Check', description: 'Analyze link profiles.', category: ToolCategory.SEO, icon: '🔗' },
  { id: 'speed-check', name: 'Page Speed', description: 'Core Web Vitals test.', category: ToolCategory.SEO, icon: '⚡' },
  { id: 'xml-valid', name: 'Sitemap Validator', description: 'Validate XML schema.', category: ToolCategory.SEO, icon: '✅' },
  { id: 'mobile-test', name: 'Mobile Friendly', description: 'Responsiveness check.', category: ToolCategory.SEO, icon: '📱' },
  { id: 'kw-density', name: 'Keyword Density', description: 'Analyze text keywords.', category: ToolCategory.SEO, icon: '📊' },
  { id: 'google-index', name: 'Index Checker', description: 'Check indexing status.', category: ToolCategory.SEO, icon: '🔎' },
  { id: 'sci-calc', name: 'Scientific Calc', description: 'Advanced math tool.', category: ToolCategory.MATH, icon: '🧮' },
  { id: 'loan-emi', name: 'Loan EMI Calc', description: 'Monthly payment estimate.', category: ToolCategory.MATH, icon: '🏦' },
  { id: 'discount-calc', name: 'Discount Calc', description: 'Calculate final price.', category: ToolCategory.MATH, icon: '🏷️' },
  { id: 'currency-conv', name: 'Currency Conv', description: 'Live exchange rates.', category: ToolCategory.MATH, icon: '💱' },
  { id: 'timezone-conv', name: 'Timezone Conv', description: 'Convert global times.', category: ToolCategory.MATH, icon: '🌍' },
  { id: 'bin-dec', name: 'Binary/Decimal', description: 'Number system converter.', category: ToolCategory.MATH, icon: '0️⃣1️⃣' },
  { id: 'fuel-eff', name: 'Fuel Efficiency', description: 'MPG to L/100km.', category: ToolCategory.UNIT, icon: '⛽' },
  { id: 'webp-png', name: 'WebP to PNG', description: 'Convert WebP to PNG.', category: ToolCategory.IMAGE, icon: '🖼️' },
  { id: 'gif-maker', name: 'GIF Maker', description: 'Basic frame assembler.', category: ToolCategory.IMAGE, icon: '🎞️' },
  { id: 'shot-pdf', name: 'Screen to PDF', description: 'Capture area to PDF.', category: ToolCategory.IMAGE, icon: '📄' },
  { id: 'img-crop', name: 'Image Cropper', description: 'Trim image borders.', category: ToolCategory.IMAGE, icon: '✂️' },
];

export const CATEGORIES = ['All', ...Object.values(ToolCategory)];
